version: '3'
services:
  postgres:
    image: postgres
    container_name: "db-api-postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./banco-de-dados:/var/lib/postgresql/data
volumes:
  banco-de-dados:

  # api:
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@postgres:5432/mydb
